#!/usr/bin/env node
// Runs as the Cloudflare Pages build command. Reads the environment
// variables set in the Cloudflare Pages dashboard (Settings -> Environment
// variables — set separately per Preview and Production environment) and
// writes config.js next to index.html so the static site can read them at
// runtime as window.APP_CONFIG.
//
// Only public-safe values belong here — see config.example.js for why the
// Supabase anon key and Turnstile site key are fine to ship to the
// browser, and why the service-role key and Turnstile secret key must
// never be added to this script or to any Pages environment variable that
// this script reads.

const fs = require("node:fs");
const path = require("node:path");

const REQUIRED_VARS = [
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUBMIT_APPOINTMENT_URL",
  "TURNSTILE_SITE_KEY",
];

const missing = REQUIRED_VARS.filter((name) => !process.env[name]);
if (missing.length > 0) {
  console.error(
    `generate-config.js: missing required environment variable(s): ${missing.join(", ")}\n` +
      "Set these in the Cloudflare Pages dashboard under Settings -> Environment variables " +
      "for this environment (Preview/dev or Production) before deploying.",
  );
  process.exit(1);
}

const config = {
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
  SUBMIT_APPOINTMENT_URL: process.env.SUBMIT_APPOINTMENT_URL,
  TURNSTILE_SITE_KEY: process.env.TURNSTILE_SITE_KEY,
};

const outputPath = path.join(__dirname, "..", "config.js");
const contents = `// AUTO-GENERATED by scripts/generate-config.js at Cloudflare Pages build
// time. Do not edit by hand or commit this file.
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outputPath, contents, "utf8");
console.log(`generate-config.js: wrote ${outputPath}`);
