-- ============================================================================
-- 0001_init_schema.sql
-- UKH Dental Clinic — core schema: enums, tables, indexes, triggers.
-- Run in order via `supabase db push` (or the Supabase SQL editor for a
-- one-off manual apply). Safe to re-run: every statement is guarded.
-- ============================================================================

-- Needed for gen_random_uuid()
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- ENUMS
-- ----------------------------------------------------------------------------
do $$ begin
  create type appointment_status as enum (
    'pending',      -- just submitted by a patient, not yet reviewed
    'contacted',    -- clinic has reached out to the patient
    'confirmed',    -- clinic and patient agreed on a time
    'completed',    -- the visit happened
    'cancelled',    -- request or confirmed visit was cancelled
    'no_show'       -- patient did not show up for a confirmed visit
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type patient_type as enum ('new', 'returning');
exception when duplicate_object then null; end $$;

do $$ begin
  create type preferred_doctor as enum ('dr_nory_ung', 'dr_muy_chem', 'no_preference');
exception when duplicate_object then null; end $$;

do $$ begin
  create type clinic_service as enum (
    'dental_cleaning_checkup',
    'tooth_filling',
    'teeth_whitening',
    'root_canal_care',
    'braces_aligners',
    'emergency_visit'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type locale_code as enum ('en', 'km');
exception when duplicate_object then null; end $$;

do $$ begin
  create type staff_role as enum ('staff', 'admin');
exception when duplicate_object then null; end $$;

-- ----------------------------------------------------------------------------
-- TABLE: appointments
-- Written to ONLY by the submit-appointment Edge Function (service role,
-- after validation/Turnstile/rate-limit checks) or by authenticated staff
-- updating status. Anonymous clients get no direct table access at all —
-- see 0002_rls_policies.sql.
-- ----------------------------------------------------------------------------
create table if not exists public.appointments (
  id                  uuid primary key default gen_random_uuid(),

  -- Non-sequential, unique, patient-facing reference (e.g. "UKH-7K3M9QXP").
  -- Generated by the Edge Function using a cryptographically random
  -- alphabet, never derived from a sequence/counter/timestamp.
  reference_number    text not null unique,

  full_name           text not null check (char_length(full_name) between 2 and 100),
  -- Normalized phone (digits, leading +, spaces/dashes stripped) by the Edge Function.
  phone               text not null check (char_length(phone) between 6 and 20),
  -- Lower-cased + trimmed by the Edge Function before insert.
  email               text not null check (char_length(email) between 5 and 254),

  patient_type        patient_type not null,
  service              clinic_service not null,
  preferred_doctor     preferred_doctor not null,
  preferred_date       date not null,
  preferred_time       text not null check (char_length(preferred_time) <= 20),

  -- Deliberately short and generic: "brief reason for visit", NOT medical
  -- history. Enforced further at the Edge Function / UI copy level.
  message              text check (char_length(message) <= 500),

  consent              boolean not null default false check (consent = true),
  locale               locale_code not null default 'en',

  status               appointment_status not null default 'pending',

  -- SHA-256 hex hash of normalized (email + phone + service + preferred_date),
  -- computed by the Edge Function. Used only to detect accidental
  -- double-submits / near-duplicate spam — never a direct identifier on its
  -- own and never displayed in the UI.
  submission_hash      text not null,

  -- SHA-256 hex hash of the submitting IP address (salted server-side).
  -- Never the raw IP — kept only long enough to support rate limiting.
  ip_hash               text,

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  -- Staff who last changed the status, for quick display without joining
  -- the audit log. The full history lives in appointment_audit_log.
  last_updated_by       uuid references auth.users(id) on delete set null
);

comment on table public.appointments is
  'Patient appointment REQUESTS. A row here is a request to be reviewed by staff, not a confirmed booking.';
comment on column public.appointments.message is
  'Brief, patient-supplied note only. Do not use for medical history or clinical detail — see product requirements.';

create index if not exists idx_appointments_status on public.appointments (status);
create index if not exists idx_appointments_created_at on public.appointments (created_at desc);
create index if not exists idx_appointments_preferred_date on public.appointments (preferred_date);
create index if not exists idx_appointments_submission_hash_created on public.appointments (submission_hash, created_at desc);
create index if not exists idx_appointments_ip_hash_created on public.appointments (ip_hash, created_at desc);
-- Case-insensitive + trimmed search across name/phone/email/reference from the staff dashboard.
create index if not exists idx_appointments_search on public.appointments
  using gin (
    to_tsvector('simple', coalesce(full_name, '') || ' ' || coalesce(phone, '') || ' ' || coalesce(email, '') || ' ' || coalesce(reference_number, ''))
  );

-- ----------------------------------------------------------------------------
-- TABLE: staff_profiles
-- One row per clinic staff member, keyed to a Supabase Auth user. Presence
-- of a row here (not just a valid JWT) is what RLS treats as "is staff".
-- Rows are created manually by an admin (via SQL editor or a future admin
-- UI) after inviting the user through Supabase Auth — there is no public
-- self-signup path.
-- ----------------------------------------------------------------------------
create table if not exists public.staff_profiles (
  user_id       uuid primary key references auth.users(id) on delete cascade,
  display_name  text not null check (char_length(display_name) between 1 and 100),
  role          staff_role not null default 'staff',
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

comment on table public.staff_profiles is
  'Marks a Supabase Auth user as clinic staff. RLS policies check membership here, not just auth.uid().';

-- ----------------------------------------------------------------------------
-- TABLE: appointment_audit_log
-- Append-only. Rows are written exclusively by the log_appointment_change()
-- trigger below (SECURITY DEFINER), never directly by staff or the Edge
-- Function, so the history can't be edited or backdated by a client.
-- ----------------------------------------------------------------------------
create table if not exists public.appointment_audit_log (
  id               uuid primary key default gen_random_uuid(),
  appointment_id   uuid not null references public.appointments(id) on delete cascade,
  changed_by       uuid references auth.users(id) on delete set null,
  field_changed    text not null,
  old_value        text,
  new_value        text,
  created_at       timestamptz not null default now()
);

create index if not exists idx_audit_log_appointment_id on public.appointment_audit_log (appointment_id, created_at desc);

-- ----------------------------------------------------------------------------
-- TABLE: rate_limit_events
-- Minimal, short-lived table backing the Edge Function's rate limiting.
-- Holds ONLY a hashed IP and a timestamp — no names, emails, or form
-- content. Old rows are pruned by prune_rate_limit_events() below.
-- ----------------------------------------------------------------------------
create table if not exists public.rate_limit_events (
  id          bigint generated always as identity primary key,
  ip_hash     text not null,
  created_at  timestamptz not null default now()
);

create index if not exists idx_rate_limit_ip_hash_created on public.rate_limit_events (ip_hash, created_at desc);

-- ----------------------------------------------------------------------------
-- TRIGGER FUNCTION: keep updated_at current
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_appointments_updated_at on public.appointments;
create trigger trg_appointments_updated_at
  before update on public.appointments
  for each row
  execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- TRIGGER FUNCTION: audit every staff-driven change
-- SECURITY DEFINER so it can insert into appointment_audit_log even though
-- staff have no direct INSERT grant on that table (see 0002_rls_policies.sql).
-- Only logs the columns staff are actually allowed to change.
-- ----------------------------------------------------------------------------
create or replace function public.log_appointment_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status then
    insert into public.appointment_audit_log (appointment_id, changed_by, field_changed, old_value, new_value)
    values (new.id, auth.uid(), 'status', old.status::text, new.status::text);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_appointments_audit on public.appointments;
create trigger trg_appointments_audit
  after update on public.appointments
  for each row
  execute function public.log_appointment_change();

-- ----------------------------------------------------------------------------
-- HELPER FUNCTION: prune rate_limit_events older than 24h.
-- Call this on a schedule (pg_cron, if enabled on the project) or simply
-- opportunistically from the Edge Function every N requests. Not required
-- for correctness, only to keep the table small.
-- ----------------------------------------------------------------------------
create or replace function public.prune_rate_limit_events()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.rate_limit_events where created_at < now() - interval '24 hours';
$$;
